name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, windows-latest]
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            
            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: '8.x'
            
            - name: Restore tools
              run: dotnet tool restore
            
            - name: Print tools available
              run: dotnet tool list --local

            - name: Redirection test
              run: dotnet run --project TestTool/TestTool.csproj
            
            - name: Print version
              run: dotnet bonsai.sgen --version
            - name: Run bonsai.sgen
              run: dotnet bonsai.sgen schema.json
